nodeLinker: node-modules

# On Windows, set enableScripts: false if isolated-vm fails to build (backend will crash at start; use WSL/Docker or Railway for full run)
enableScripts: false

yarnPath: .yarn/releases/yarn-4.4.1.cjs
