nodeLinker: node-modules

# Note: We keep scripts enabled by default so native modules like isolated-vm
# are built correctly in Linux/Docker/Railway.
# If local Windows installs fail, you can temporarily run:
#   $env:YARN_ENABLE_SCRIPTS = \"0\"
# before running `yarn install` in your local shell.

yarnPath: .yarn/releases/yarn-4.4.1.cjs
